# Helm values for app python-demo

appName: python-demo
namespace: python-demo-ns-dev

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
