# Helm values for app python-111

appName: python-111
namespace: python-111-ns-dev

image:
  repository: ghcr.io/nishank841/budget-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
