# Helm values for app python-atlas

appName: python-atlas
namespace: python-atlas-ns-dev

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
