# Helm values for app python-chikks

appName: python-chikks
namespace: python-chikks-ns-dev

image:
  repository: nishank840/python-chikks
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
