# Helm values for app python-url

appName: python-url
namespace: python-url-ns-dev

image:
  repository: ghcr.io/nishank841/budget-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
