# Helm values for app python-argocd

appName: python-argocd
namespace: python-argocd-ns-dev

image:
  repository: nishank840/python-argocd
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
