# Helm values for app python-555

appName: python-555
namespace: python-555-ns-dev

image:
  repository: ghcr.io/nishank841/budget-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
