# Helm values for app python-bash

appName: python-bash
namespace: python-bash-ns-dev

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
