# Helm values for app python-example

appName: python-example
namespace: python-example-ns-dev

image:
  repository: nishank840/python-example
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
