# Helm values for app python-test

appName: python-test
namespace: python-test-ns-dev

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: false
