name: Auto Merge PRs

on:
  pull_request:
    types: [opened, labeled, synchronize]

# ADD THIS SECTION
permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - uses: actions/checkout@v3
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          token: ${{ secrets.GITHUB_TOKEN }}
