name: Helm Build

on:
  push:
    paths:
      - 'apps/**'

jobs:
  detect-and-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Detect Changed File
        id: changed
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Template Chart (Validation)
        run: |
          for file in apps/*.yaml; do
            echo "Validating $file"
            helm template charts/base-app -f $file > /dev/null
          done
