# Helm values for app python-rename

appName: python-rename
namespace: python-rename-ns-dev

image:
  repository: nishank840/python-rename
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
